### ISSUE TITLE
[request] Windows support

### ISSUE THREAD

**Issue by olivebishop** [midday-ai/languine#17]
## Introduction 

- Getting an error yet I have Ollama installed on Windows 11. The problem occurs when I run the CLI and choose Ollama I get this -:
## steps
  What would you like to do?
│  Initialize a new Languine configuration
┌  Let's set up your i18n configuration
│
◇  What is your source language?
│  English
│
◇  What languages do you want to translate to?
│   es,fr,de,ja,sw,ar,zh
│
◇  Where should language files be stored?
│  app/locales
│
◇  What format should language files use?
│  TypeScript (.ts)
│
◇  Which provider would you like to use?
│  Ollama
'which' is not recognized as an internal or external command,
operable program or batch file.
│
└  Ollama binary not found. Please install Ollama

**Comment by pontusab** [comment]
Thanks for adding this issue, unfortunately I don't own a windows so need the community to help me here.

**Comment by ademajagon** [comment]
The command is correct, but the OS is wrong. `which` is a Unix command, not a Windows one. On Windows, you should use `where` instead.

You can also set an alias for `which`:
`Set-Alias which where.exe`

**Comment by ademajagon** [comment]
I've created a PR that resolves this issue by replacing the `which` command with `where` for win: https://github.com/midday-ai/languine/pull/38

**Comment by pontusab** [comment]
fixed in 1.0.2, out in a few minutes!
