### ISSUE TITLE
Feature Request: Automated Detection and Population of Source Locale File

### ISSUE THREAD

**Issue by Heet-Bhalodiya** [midday-ai/languine#25]
Hi Team,

First of all, thank you for creating such an amazing tool that simplifies the localization process! It's been incredibly helpful, and I appreciate the effort that has gone into developing Languine.

I wanted to suggest a feature that could make the tool even more user-friendly, especially for projects with large codebases:

Currently, to update, delete, or add translation keys, we need to provide a base/source file (e.g., `en.json`, `ts`, `mdx`). However, for large projects, manually listing all the keys and values in the source file can be quite challenging and time-consuming. This process becomes a bottleneck for applying translations across all text in a project.

Since Languine already uses OpenAI’s API, I believe it could potentially analyze the project and generate a tree structure by recursively scanning the specified folder(s). This would allow users to provide the folder path they want to analyze, and the tool could automatically populate the base/source locale file with the keys and values it identifies. 

This feature would be a significant relief for users with large projects, enabling them to get a comprehensive source file without manually compiling it. Afterward, users can easily convert the base locale into other languages using the existing features.

Thank you for considering this suggestion! I believe it could greatly enhance the tool's usability and efficiency. Please let me know if you need any further clarification.

Best regards

**Comment by pontusab** [comment]
yes I will think of a extract command with AST starting with typescript/js!

**Comment by pontusab** [comment]
https://x.com/pontusab/status/1873033541765988477?s=46&t=EsyqrpgYWcCvn97nnTxwww

**Comment by pontusab** [comment]
Out in `0.7.1`
