### ISSUE TITLE
Presets for libraries and formats

### ISSUE THREAD

**Issue by pontusab** [midday-ai/languine#3]
Figure out used library and apply more specific instructions.

**Comment by fuma-nama** [comment]
+ Markdown formats, I can submit a PR for Markdown support & Fumadocs preset

**Comment by psteinroe** [comment]
Support for po files would also be great. Thanks for the great work 🫶🏼

**Comment by fuma-nama** [comment]
Would you mind me to use Vitest for unit tests? I found unit tests are not configured but Vitest's file snapshot feature is pretty nice

**Comment by pontusab** [comment]
whatever works best for you! we can also use bun directly!
