### ISSUE TITLE
yarn error

### ISSUE THREAD

**Issue by marc-on-github** [midday-ai/languine#39]
◇  What would you like to do?
│  Initialize a new Languine configuration
┌  Let's set up your i18n configuration
│
◇  What type of config file would you like to use?
│  TypeScript
│
◇  Failed to install Languine
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: yarn install languine -D
error `install` has been replaced with `add` to add new dependencies. Run "yarn add languine --dev" instead.

**Comment by pontusab** [comment]
Fixed in `languine@1.0.1`

**Comment by amannn** [comment]
@pontusab I just ran into the same error:

```
❯ pnpx languine@latest init --p=prj_XXX
┌  Initialize a new Languine configuration
│
◇  What is your source language?
│  English
│
◇  What languages do you want to translate to?
│  es-MX, en-CA, fr-CA
│
◇  Select file format
│  JSON (.json)
│
◇  Enter the file pattern for translations
│  messages/[locale].json
│
◇  Select configuration format
│  TypeScript (languine.config.ts)
│
◇  Failed to install Languine
│
└  Failed to create configuration file

Error: Command failed: yarn install languine -D
error `install` has been replaced with `add` to add new dependencies. Run "yarn add languine --dev" instead.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'yarn install languine -D'
}
```

Is there a workaround?

**Comment by pontusab** [comment]
Try now with 2.0.7, we are now failing gracefully if we can't figure out the package manager, then you can install the dependency manually!

**Comment by amannn** [comment]
Works now, thanks @pontusab! 🙌

**Comment by pontusab** [comment]
I'm going to remove support for TS right now fyi 🥲
